### ISSUE TITLE
Specifying options inline does not work properly

### ISSUE THREAD

**Issue by sirianni** [eliangcs/http-prompt#107]
When trying to specify a param inline, the input does not accept a `space` character after the URL.  Note below the lack of space between `/api/something` and `page==2`.  The cursor also resets to position 0 in this situation.

![output](https://cloud.githubusercontent.com/assets/381302/22701780/a88abaf6-ed2c-11e6-9b18-0749fbe0ea7e.gif)

The command actually works, but the command line processing is not handled properly.

**Comment by eliangcs** [comment]
Fixed in v0.9.2.
