### ISSUE TITLE
Add 'reset' Command

### ISSUE THREAD

**Issue by Miserlou** [eliangcs/http-prompt#12]
Hey @eliangcs !

Awesome tool. I'm clearly going to get a lot of use out of this. I'm going to file a bunch of tickets now as feature requests. I'm sure you've thought about lots of these, but if we have them as individual Issues then we can discuss them/track changes/assign them, etc.

The first would be a simple 'reset' command. I like the current default behavior that 'name=jack' will persist, but I'd like to be able to reset it with a single command.

**Comment by eliangcs** [comment]
I'd probably name it `rm *` to allow users to clear all the settings they have.

**Comment by eliangcs** [comment]
`rm *` has been added in PR #34. Closing.
