### ISSUE TITLE
Python 2.6: `ordereddict` from PyPI?

### ISSUE THREAD

**Issue by delirious-lettuce** [eliangcs/http-prompt#124]
I was looking at [Raymond Hettinger's script](https://code.activestate.com/recipes/576693/) on ActiveState (in this repo as `ordereddict.py`) and noticed in the comments that it was [available on PyPI](https://pypi.python.org/pypi/ordereddict). It seems to be an updated version of the original script.

I guess I'm just wondering if it wouldn't be easier to just `pip install ordereddict` (by adding it to `requirements.txt`)?

**Comment by eliangcs** [comment]
I didn't add it to requirements.txt because I couldn't find a way to tell pip to install `ordereddict` only for Python 2.6. I don't want users to install `ordereddict` if they are using Python 2.7-3.6. Do you happen to know how to do it?

**Comment by delirious-lettuce** [comment]
My original thought was that it was kind of "installed" for Python 2.7-3.6 users anyways (in the form `ordereddict.py`), so why not just pip install it. But you make a good point, having it installed only when needed (Python 2.6 users) seems like the better option.

I came across a few links while looking for solutions (I was googling "conditional dependencies python"):

* https://hynek.me/articles/conditional-python-dependencies/
* https://gist.github.com/petermelias/8481395
* https://stackoverflow.com/questions/19672980/can-you-set-conditional-dependencies-for-python-2-and-3-in-setuptools

**Comment by eliangcs** [comment]
@delirious-lettuce I think that works 👍. Feel free to create a pull request if you want to. Thanks a lot!

**Comment by delirious-lettuce** [comment]
Ok, sure. I'll be at my computer in maybe 45-60 minutes. I'll do a couple
tests and then submit that PR.
