### ISSUE TITLE
load HTTP Prompt environment from command line

### ISSUE THREAD

**Issue by tardypad** [eliangcs/http-prompt#131]
It would be convenient to be able to load a HTTP Prompt environment from the command line so as to launch http-prompt with a predefined context without requiring any manual input within http-prompt. Currently the only way to fully load such an environment is to execute `exec /path/to/project.hp` interactively.
Loading an environment in such a way would allow the creation of aliases

I'm thinking of 2 different ways to do this:
- Option 1:
add a `--env` cli parameter to would take the environment file to load as parameter
`http-prompt --env /path/to/project.hp`
- Option 2:
support receiving data from stdin
`cat /path/to/project.hp | http-prompt`

Each of these option would make it possible to create aliases:
- Option 1
`alias http_project_prod='http-prompt --env /path/to/project_prod.hp`
`alias http_project_test='http-prompt --env /path/to/project_test.hp`
- Option 2
`alias http_project_prod='cat /path/to/project_prod.hp | http-prompt'`
`alias http_project_test='cat /path/to/project_test.hp | http-prompt'`

Please let me know what you think of it
I'm willing to implement it myself if

**Comment by tardypad** [comment]
I did a bit of research already and the option 2 might turn to be more tricky.

The prompt-toolkit doesn't support piping (see https://github.com/jonathanslenders/python-prompt-toolkit/issues/502) and will actually "crash" in such a case

We could surely use the snippet mentioned in that previous issue
```
if not sys.stdin.isatty():
    data = sys.stdin.read()
```
and load the context from this data but the prompt still exits (from  https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/input.py#L67), unless we overwrite `stdin` afterwards `sys.stdin = sys.stdout`
It looks hacky and I don't know if that would cause issues...

Probably the other option would be not to use the `prompt` shortcut but to build our own CommandLineInterface instance (as mentioned in http://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#module-prompt_toolkit.shortcuts)

So if you're ok with the option 1 of the `--env` cli parameter, it should be much easier to implement I believe

**Comment by eliangcs** [comment]
I tried it before, receiving data from stdin in a prompt-toolkit app is indeed not an easy thing to do. So I think we can add a `--env` option in the cli. Free feel the implement it. Thanks!
