### ISSUE TITLE
Make it possible to see what the request will look like

### ISSUE THREAD

**Issue by curioussavage** [eliangcs/http-prompt#134]
Hey, love the tool. I like that you can use `httpie` to see what it will pass to the command but I would like to see what the request is going to look like (formatted nicely). Or an option to print out the request each response.

**Comment by eliangcs** [comment]
@curioussavage it's probably similar to #40, printing raw HTTP request format. Before we add this feature, you can use httpie's `--verbose` option to print the request before each response.

**Comment by curioussavage** [comment]
Cool. I will give that arg a try.

**Comment by eliangcs** [comment]
Closing this one as duplicate.
