### ISSUE TITLE
Allow launching with options & settings

### ISSUE THREAD

**Issue by kofalt** [eliangcs/http-prompt#14]
Awesome project! :+1: 

I have an endpoint that I hit with an invalid cert & various headers:

```
http --verify=no POST https://localhost...  'Authorization:...'
```

I would love to make a script to launch `http-prompt` with that already prepared.
My current understanding is that I can set up the URL, but not the `--verify` or `Authorization` parts.

**Comment by eliangcs** [comment]
See PR #19. I'll review and merge it when I have time.

**Comment by eliangcs** [comment]
Done in #19. Closed.
