### ISSUE TITLE
command not found: http-prompt

### ISSUE THREAD

**Issue by speedcell4** [eliangcs/http-prompt#2]
`sudo python3.5 -m pip install http-prompt` but `command not found` error shown.

OS X 10.11.2
Python 3.5.1
pip 8.1.2

**Comment by Toybreak** [comment]
``` shell
zsh: command not found: http-prompt
```
same issue

**Comment by eliangcs** [comment]
It's likely a Python version or path issue instead of a bug of HTTP Prompt. What's your output of the following commands?

```
which python
which python3.5
which pip
which pip3.5
```

**Comment by speedcell4** [comment]
```shell
➜  ~ which python
/usr/local/bin/python
➜  ~ which python3.5
/usr/local/bin/python3.5
➜  ~ which pip
/usr/local/bin/pip
➜  ~ which pip3.5
/usr/local/bin/pip3.5
```

**Comment by kazuar** [comment]
Maybe try to install it on a virtualenv? (worked for me)

**Comment by speedcell4** [comment]
@kazuar still not works for me.

**Comment by skenbo0916** [comment]
Encountered this initially, solved with `$ sudo pip install http-prompt`

**Comment by macmacbr** [comment]
same problem here: 
python installed from brew: 2.7.11
$ which python
/usr/local/bin/python
$ python -V
Python 2.7.11
$ which pip
/usr/local/bin/pip
$ pip -V
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
$ pyenv
pyenv 20160509-7-g97da7c4

**Comment by eliangcs** [comment]
Try looking for an executable file named `http-prompt` in your Python bin directory, e.g., `/System/Library/Frameworks/Python.framework/Versions/2.7/bin`. If you can find `http-prompt`, that means you should probably add the bin directory to your PATH environment variable.

**Comment by speedcell4** [comment]
@eliangcs Thank you, this works for me. Since I use Python 3.5, the path for me is `/Library/Frameworks/Python.framework/Versions/3.5/bin`
