### ISSUE TITLE
support white terminal

### ISSUE THREAD

**Issue by donalmurtagh** [eliangcs/http-prompt#24]
The color scheme makes this almost unusable on a white terminal.
![screen shot 2016-05-25 at 11 57 41](https://cloud.githubusercontent.com/assets/11269693/15537739/f50f3736-226f-11e6-937c-38a96b706811.png)

**Comment by eliangcs** [comment]
Fixed in PR #45. The default style will be set to 'solarized', which looks good on both light and dark background.

**Comment by arve0** [comment]
Could you give a heads up when you're releasing this?

**Comment by eliangcs** [comment]
The next release (v0.4.0) will be in this week.
