### ISSUE TITLE
Any way to persist options?

### ISSUE THREAD

**Issue by bbuck** [eliangcs/http-prompt#4]
I decided to test this while implementing some changes to an endpoint. I need to make the same request back to back. Hitting "up" and using the same line to set headers is not horrible, but it would be nice and interesting (and makes sense with the tool, IMO) if I could persist these settings until a clear them. Even if this an opt-into kind of behavior I think it would be nice and would definitely encourage me to use this over something like Postman where I can enter everything once and just keep hitting the "GET" button.

**Comment by eliangcs** [comment]
I'm not getting your point. As long as you're in a session (not leaving http-prompt), the state should be persistent. Can you give me an example of your use case?

**Comment by bbuck** [comment]
Yea, I'm still playing with it. The first time I ran this (when I made the request) the headers I set were not persisted. But a few minutes ago I had an issue where the headers were being persisted (and I had forgotten they were).

Is there a way to clear the currently provided settings?

**Comment by eliangcs** [comment]
Currently, there is no way to reset all the settings using a single command. But I'm planning to add the feature soon.

**Comment by bbuck** [comment]
Sounds good. I'm going to close this issue since it's really a non-issue. Thanks for the awesome tool!
