### ISSUE TITLE
Remove quotes from request

### ISSUE THREAD

**Issue by aray12** [eliangcs/http-prompt#5]
First, I love to tool. Seems like a much less painful way to do some ad hoc testing during dev.

So I am trying to submit a request using JWT authorization. It looks like Httpie has a plugin for this, but I am trying to get it working without that. The problem is that the request still includes quotation marks that causes it to fail

    http-prompt localhost/api/account

    Authorization:'Bearer <jwt>'
    get

What I want is

    Authorization: Bearer <jwt>

But according to my logs I am getting 

    Authorization: 'Bearer <jwt>'

Any suggestions?

**Comment by eliangcs** [comment]
Thanks for reporting the bug. Fixed in master branch. Will release a new version soon.
