### ISSUE TITLE
http-prompt immediately exits upon receiving an interrupt without prompting for confirmation

### ISSUE THREAD

**Issue by SirBraneDamuj** [eliangcs/http-prompt#52]
I find myself exiting the program accidentally very often. 

When using a shell like bash, I will often use Ctrl-C interrupts to abort my current prompt and start again. It would be super cool if http-prompt worked the same way.

Currently, an interrupt will exit the program without confirmation. That is problematic because my natural inclination when making a typo in a prompt is to Ctrl-C and retype it.

Using interrupts to exit is still fine, as long as it has some form of confirmation first. Other shells do things like:

* Press Ctrl-C twice in a row to exit
* Ask for a confirmation (Yn)

Also common is for an interrupt to just start a fresh prompt, which is what I would personally prefer.

**Comment by eliangcs** [comment]
Fixed in PR #53.
