### ISSUE TITLE
rm -[b,h,o,q] should delete all parameters of given type

### ISSUE THREAD

**Issue by fogine** [eliangcs/http-prompt#79]
This enhancement would allow us to delete all parameters of given type when we don't provide specific parameter index.

I can implement this when I get some free time if you agree with this feature @eliangcs .

**Comment by eliangcs** [comment]
I think users should add a `*` at the end to delete all parameters of a given type. For example:

```
rm -q *
rm -b *
```

@fogine what do you think?

**Comment by fogine** [comment]
yeah, I agree, @eliangcs

**Comment by eliangcs** [comment]
Done in PR #81.
