### ISSUE TITLE
Is it possible to use VI-mode?

### ISSUE THREAD

**Issue by ilya-bystrov** [eliangcs/http-prompt#85]
It looks like python-prompt-toolkit supports vi mode: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/docs/pages/building_prompts.rst#vi-input-mode and also supports dynamic switching between emacs and vi mode.

I think, it will be wonderful to use vi mode in http-prompt.

**Comment by eliangcs** [comment]
Yes, it's possible and should be easy to do. Let's include this in the next release.

**Comment by eliangcs** [comment]
The feature was added in PR #94 and merged to master. To enable vi mode, add this line in your config file:

```
vi = True
```
