### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [eliangcs/http-prompt#96]
Dear Chang-Hung,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by ethanhs** [comment]
@sergeevabc you don't need a compiler. It is Python, which is an interpreted language. You should just need to go to https://python.org and download Python, then run the install command. `pip install http-prompt`. Then you should be able to just run `http-prompt`.

**Comment by sergeevabc** [comment]
Thank you for letting me know.
I hoped for standalone solution without dependencies.

**Comment by eliangcs** [comment]
@sergeevabc Making a standalone binary is not a priority unless many users request it.

**Comment by sergeevabc** [comment]
I’m told that [py2exe][1] might help you to convert Python project into standalone executable. Care to try?

[1]: http://py2exe.org/
